# Generated by Django 2.2.9 on 2020-02-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=52, primary_key=True)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=16)),
                ('org_name', models.TextField()),
            ],
        ),
    ]
