# Generated by Django 2.2.9 on 2020-02-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsc', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(max_length=80)),
                ('website_url', models.TextField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
